[colors.primary]
background = '#111318'
foreground = '#e1e2e9'

[colors.cursor]
text = '#e1e2e9'
cursor = '#c4c6cf'

[colors.vi_mode_cursor]
text = '#111318'
cursor = '#a8c8ff'

[colors.search.matches]
foreground = '#43474e'
background = '#dbbce1'

[colors.search.focused_match]
foreground = '#43474e'
background = '#a8c8ff'

[colors.footer_bar]
foreground = '#43474e'
background = '#e1e2e9'

[colors.hints.start]
foreground = '#43474e'
background = '#bdc7dc'

[colors.hints.end]
foreground = '#43474e'
background = '#bdc7dc'

[colors.selection]
text = '#111318'
background = '#a8c8ff'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#a8c8ff'
yellow = '#3e5f90'
blue = '#a8c8ff'
magenta = '#dbbce1'
cyan = '#bdc7dc'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
