#! /bin/sh
# File              : bspwmrc
# Author            : I'mCylon <imcylonrs@gmail.com>
# Date              : 01.08.2021
# Last Modified Date: 17.08.2021
# Last Modified By  : I'mCylon <imcylonrs@gmail.com>

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config border_width        3
bspc config border_radius       7
bspc config window_gap          15
bspc config normal_border_color     \#808080
bspc config focused_border_color    \#FF0000
bspc config presel_feedback         \#FF00FF

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# startup wallpaper
wpp=$(find /home/pictures/wallpaper -name '*.*' | shuf -n1) && hsetroot -fill $wpp

# startup
# killall polybar
# sh ~/.config/polybar/launch.sh --imcylon
killall picom
sudo killall crond
sudo /usr/sbin/crond
xsetroot -cursor_name left_ptr

# floating windows
bspc rule -a krunner border=off
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a systemsettings state=floating rectangle=1200x700+100+190
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a kalarm state=floating
# bspc rule -a Gucharmap state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Screenkey manage=off
/usr/bin/picom
