[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.cursor]
text = '#e2e2e9'
cursor = '#c4c6d0'

[colors.vi_mode_cursor]
text = '#111318'
cursor = '#adc6ff'

[colors.search.matches]
foreground = '#44474f'
background = '#debcdf'

[colors.search.focused_match]
foreground = '#44474f'
background = '#adc6ff'

[colors.footer_bar]
foreground = '#44474f'
background = '#e2e2e9'

[colors.hints.start]
foreground = '#44474f'
background = '#bfc6dc'

[colors.hints.end]
foreground = '#44474f'
background = '#bfc6dc'

[colors.selection]
text = '#111318'
background = '#adc6ff'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#adc6ff'
yellow = '#445e91'
blue = '#adc6ff'
magenta = '#debcdf'
cyan = '#bfc6dc'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
