#!/bin/bash
# File              : slack
# Author            : I'mCylon <imcylonrs@gmail.com>
# Date              : 16.01.2023
# Last Modified Date: 16.01.2023
# Last Modified By  : I'mCylon <imcylonrs@gmail.com>
telegram-desktop

